import NavBar from "@/components/navbar";
import SideBar from "@/components/sidebar";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
    title: "Nara RAG",
    description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
    return (
        <div className="h-full w-full">
            <div className="fixed">
                <NavBar />
            </div>

            <div className="md:flex mt-[72px] flex-col fixed inset-y-0">
                <SideBar />
            </div>
            <main className="md:pl-[90] h-full w-full pt-[72]"> {children}</main>
        </div>
    );
};

export default RootLayout;
